stages:
  - test
  - analyse

test:unit:
  stage: test
  image: registry.cubesystems.lv/latvenergo/docker/leonardo/base:8.0-composer-2
  before_script:
    - composer install --ignore-platform-reqs --no-scripts
  script:
    - ./vendor/bin/pest --coverage-clover=coverage.xml
  artifacts:
    when: always
    paths:
      - coverage.xml
    expire_in: 1 day

sonarqube-check:
  stage: analyse
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [ "" ]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  before_script:
    - sed -i -e 's?/app?'`pwd`'?' coverage-report.xml
    - sed -i -e 's?/app?'`pwd`'?' phpunit-report.xml
  script:
    - sonar-scanner
  allow_failure: true
