stages:
  - test
  - analyse

test:unit:
  stage: test
  image: registry.cubesystems.lv/latvenergo/docker/leonardo/base:8.0-soap-revision
  before_script:
    - mv /usr/local/etc/php/conf.d/disabled/docker-php-ext-pcov.ini /usr/local/etc/php/conf.d/docker-php-ext-pcov.ini
    - composer install --no-scripts
  script:
    - ./vendor/bin/pest --coverage --coverage-clover=coverage.xml
  artifacts:
    when: always
    paths:
      - coverage.xml
    expire_in: 1 day

sonarqube-check:
  stage: analyse
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
  allow_failure: true
